apiVersion: v1
kind: Service
metadata:
   name: strapi
spec:
   selector:
      io.kompose.service: strapi
   ports:
      - protocol: TCP
        port: 1337
        targetPort: 1337
   type: ClusterIP
