apiVersion: apps/v1
kind: Deployment
metadata:
   name: strapi
spec:
   replicas: 1
   selector:
      matchLabels:
         io.kompose.service: strapi
   template:
      metadata:
         labels:
            io.kompose.service: strapi
      spec:
         containers:
            - env:
                 - name: NODE_ENV
                   value: production
                 - name: DATABASE_CLIENT
                   value: postgres
                 - name: DATABASE_HOST
                   value: postgres
                 - name: DATABASE_PORT
                   value: "5432"
                 - name: DATABASE_NAME
                   value: postgres
                 - name: DATABASE_USERNAME
                   value: postgres
                 - name: DATABASE_PASSWORD
                   value: {{ .Values.postgres_password | b64dec | quote }}
                 - name: DATABASE_SSL
                   value: "false"
                 - name: EXTRA_ARGS
                   value: "--debug"
                 - name: API_TOKEN_SALT
                   value: {{ .Values.postgres_password | quote }}
                 - name: PUBLIC_URL
                   value: {{ .Values.strapi_public_url | quote }}
                 - name: ADMIN_JWT_SECRET
                   value: {{ .Values.postgres_password | quote }}
                 - name: STRAPI_DISABLE_UPDATE_NOTIFICATION
                   value: "true"
              image: strapi-demo:latest
              name: strapi
              ports:
                 - containerPort: 1337
              imagePullPolicy: IfNotPresent
